### ISSUE TITLE
Invalid Firefox binary

### ISSUE THREAD

**Issue by hasanparasteh** [ManivannanMurugavel/tor-browser-selenium#1]
Hi thanks for your great post on medium blog
I want to create a Tor Browser automation but when I want to run the program I get this message:
`tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary`
I even use your code and dosen't change anything and I get the same error message do you have any idea?
Python Version: 2.7
OS: Linux Ubuntu 18.0.4
Error Code: `Traceback (most recent call last):
  File "tor_browser_example.py", line 5, in <module>
    with TorBrowserDriver("/home/hp/.local/share/tor-browser_en-US/Browser") as driver:
  File "/home/hp/.local/lib/python2.7/site-packages/tbselenium/tbdriver.py", line 44, in __init__
    tbb_profile_path, tor_data_dir)
  File "/home/hp/.local/lib/python2.7/site-packages/tbselenium/tbdriver.py", line 124, in setup_tbb_paths
    % tbb_fx_binary_path)
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary /home/hp/.local/share/tor-browser_en-US/Browser/Browser/firefox`

**Comment by ManivannanMurugavel** [comment]
Hi @hasanparasteh,
Please follow the step 2 from this blog

Link: https://medium.com/@manivannan_data/selenium-with-tor-browser-using-python-7b3606b8c55c
